version: 2.1

jobs:
  build:
    docker:
      - image: cypress/base:14.17.0
    steps:
      - checkout
      - run:
          name: Instalar dependencias
          command: |
            apt-get update
            apt-get install -y libnss3
      - run:
          name: Instalar dependencias Node.js
          command: npm install
      - run:
          name: Empezar la aplicacion y los tests
          command: |
            npx start-server-and-test start http://localhost:4100 cypress:test

  deploy:
    docker:
      - image: google/cloud-sdk:latest
    steps:
      - checkout
      - run:
          name: Autentificarse en GCP
          command: |
            echo $GCLOUD_SERVICE_KEY | base64 --decode > ${HOME}/gcloud-service-key.json
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            if [ -z "$GCP_PROJECT_ID" ]; then
              echo "Error GCP_PROJECT_ID"
              exit 1
            fi
            gcloud config set project $GCP_PROJECT_ID
            if [ -z "$GKE_CLUSTER" ]; then
              echo "Error GKE_CLUSTER"
              exit 1
            fi
            if [ -z "$GCP_ZONE" ]; then
              echo "Error GCP_ZONE"
              exit 1
            fi
            gcloud container clusters get-credentials $GKE_CLUSTER --zone $GCP_ZONE --project $GCP_PROJECT_ID
      - run:
          name: Desplegar GKE
          command: |
            kubectl apply -f k8s/

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build

