version: 2.1

jobs:
  build:
    docker:
      - image: cypress/base:14.17.0
    steps:
      - checkout
      - run:
          name: Install system dependencies
          command: |
            apt-get update
            apt-get install -y libnss3
      - run:
          name: Install Node.js dependencies
          command: npm install
      - run:
          name: Start the application and run tests
          command: |
            npx start-server-and-test start http://localhost:4100 cypress:test

  deploy:
    docker:
      - image: google/cloud-sdk:latest
    steps:
      - checkout
      - run:
          name: Authenticate to GCP
          command: |
            echo $GCLOUD_SERVICE_KEY | base64 --decode > ${HOME}/gcloud-service-key.json
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            if [ -z "$GCP_PROJECT_ID" ]; then
              echo "GCP_PROJECT_ID is not set"
              exit 1
            fi
            gcloud config set project $GCP_PROJECT_ID
            if [ -z "$GKE_CLUSTER" ]; then
              echo "GKE_CLUSTER is not set"
              exit 1
            fi
            if [ -z "$GCP_ZONE" ]; then
              echo "GCP_ZONE is not set"
              exit 1
            fi
            gcloud container clusters get-credentials $GKE_CLUSTER --zone $GCP_ZONE --project $GCP_PROJECT_ID
      - run:
          name: Deploy to GKE
          command: |
            kubectl apply -f k8s/

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build

